# Generated by Django 4.2.4 on 2023-08-31 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('profile_picture_url', models.URLField(blank=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=12)),
                ('preferred_materials', models.TextField(blank=True)),
                ('budget_range', models.CharField(blank=True, max_length=100)),
                ('ratings', models.FloatField(default=0.0)),
                ('verified_seller', models.BooleanField(default=False)),
                ('business_name', models.CharField(blank=True, max_length=100)),
                ('materials_in_stock', models.TextField(blank=True)),
                ('delivery_time', models.CharField(blank=True, max_length=100)),
                ('delivery_radius', models.CharField(blank=True, max_length=100)),
                ('wishlist', models.TextField(blank=True)),
                ('payment_details', models.TextField(blank=True)),
                ('shipping_preferences', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_seller', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified')], default='pending', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
