# Generated by Django 4.2.4 on 2023-12-06 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_conversation_alter_item_material_alter_item_seller_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='is_available',
            new_name='isForSale',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='isPriceNegotiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='seller',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
