# Generated by Django 5.0 on 2023-12-20 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_is_available_item_isforsale_item_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='main_app.item'),
        ),
    ]
