# Generated by Django 4.2 on 2024-08-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_item_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='number_of_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
